import numpy as np

FS = 48000
V = 343.0
R = 0.06

def get_theoretical_delays(angle):
    rad = np.radians(angle)
    dL0 = (R * np.cos(rad)) / V * FS
    dR0 = (R * np.sin(rad)) / V * FS
    dR1 = (-R * np.cos(rad)) / V * FS
    dL1 = (-R * np.sin(rad)) / V * FS
    return dL0, dR0, dR1, dL1

with open('src/srp_lut.h', 'w') as f:
    f.write("#ifndef SRP_LUT_H\n")
    f.write("#define SRP_LUT_H\n\n")
    f.write("// Precomputed SRP-PHAT delays for 6 microphone pairs over 360 degrees\n")
    f.write("// Generated by Python script. Do not modify manually.\n")
    f.write("// Pairs: 0:L0-R0, 1:L0-R1, 2:L0-L1, 3:R0-R1, 4:R0-L1, 5:R1-L1\n\n")
    
    f.write("const float srp_delays[6][360] = {\n")
    for pair_idx in range(6):
        f.write("    { ")
        for theta in range(360):
            dL0, dR0, dR1, dL1 = get_theoretical_delays(theta)
            
            if pair_idx == 0: val = dL0 - dR0
            elif pair_idx == 1: val = dL0 - dR1
            elif pair_idx == 2: val = dL0 - dL1
            elif pair_idx == 3: val = dR0 - dR1
            elif pair_idx == 4: val = dR0 - dL1
            elif pair_idx == 5: val = dR1 - dL1
            
            f.write(f"{val:.4f}f")
            if theta < 359: f.write(", ")
        f.write(" }")
        if pair_idx < 5: f.write(",")
        f.write("\n")
    f.write("};\n\n")
    f.write("#endif // SRP_LUT_H\n")
print("✅ Successfully generated src/srp_lut.h")