[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 256000

; Kích hoạt PSRAM cho dòng R8 (OPI)
board_build.arduino.memory_type = qio_opi 
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -O3